config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#welcome'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'welcome' => 'welcome#welcome'
  get 'about' => 'welcome#about'
  get 'signup' => 'users#new'
  get 'blog' => 'stories#index'
  get 'tag_cloud' => 'tags#show'

  post 'email_responses/bounce' => 'email_responses#bounce'
  post 'email_responses/complaint' => 'email_responses#complaint'

  get '/admin',   to: 'admin_pages#main'
  get '/admin/users',   to: 'admin_pages#admin_users'
  get '/admin/stories',   to: 'admin_pages#admin_stories'

  get 'stories/sort' => 'stories#sort'
  get 'stories/search' => 'stories#search'

  resources :users do
    resources :stories
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :stories do
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :comments do
    resources :comments
  end

  resources :pictures do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :recordings do
    resources :comments
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
    @stories = Story.order("RANDOM()").limit(3)
    @pictures = Picture.order("RANDOM()").limit(3)
    @videos = Video.order("RANDOM()").limit(3)
    @stories_with_recordings = Story.joins(:recordings).order("RANDOM()").limit(3)
    @user_recordings = Recording.where(recordable_type: "User").order("RANDOM()").limit(4)
    @guestbook_comments = Comment.where(commentable_type: "User")
  end

  def about
  end

end

app/views/welcome/_blog.html.erb
<section id="blog">
  <div class="container text-center wow fadeIn">
    <h4>Stories</h4>
    <hr class="pageLine" />
    <div>
      <a href=" <%= stories_path %> " class="btn btn-default btn-lg buttonDropShadow" id="storiesButton" role="button" data-toggle="tooltip" title="Click to see the full list of stories">Full List</a>
    </div>
    <% @stories.each do |story| %>
      <a href="<%= story_path(story.id) %>" class="blog_links">
        <div class="row panel panel-default box-shadow">
          <div class="panel-body">
            <% if story.picture.attached? %>
              <div class="col-md-5">
                <div>
                  <%= image_tag story.picture, alt: "Thumbnail", class: "img-responsive center-picture" %>
                </div>
              </div>
              <div class="col-md-7">
                <div class="caption black">
                  <h3 class="MajestiBannerBookPartial">
                    <%= story.title %>
                  </h3>
                  <div class="MajestiBannerBookParaPartial text-left">
                    <%= raw Truncato.truncate(story.content.body.to_html, max_length: 400) %>
                  </div>
                </div>
                 <% if story.recordings.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has an audio recording"><i class="far fa-file-audio fa-2x"></i></div>
                <% end %>
                <% if story.comments.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has comments"><i class="far fa-comments fa-2x"></i></div>
                <% end %>
              </div>
            <% else %>
              <div class="col-md-12">
                <div class="caption black">
                  <h3 class="MajestiBannerBookPartial">
                    <%= story.title %>
                  </h3>
                  <div class="MajestiBannerBookParaPartial text-left">
                    <%= raw Truncato.truncate(story.content.body.to_html, max_length: 400) %>
                  </div>
                </div>
                 <% if story.recordings.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has an audio recording"><i class="far fa-file-audio fa-2x"></i></div>
                <% end %>
                <% if story.comments.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has comments"><i class="far fa-comments fa-2x"></i></div>
                <% end %>
              </div>
            <% end %> <% if story.word_count != nil %>
              <div class="col-md-12">
                <div class="float-right black">
                  <p class="MajestiBannerBookPartial">
                    Estimated Reading Time: <% if (story.word_count / 130.0) > 1 %> <%= (story.word_count / 130.0).round(1) %> minutes <% else %> 1 minute <% end %>
                  </p>
                </div>
              </div>
            <% end %>
          </div>
          <% if story.all_tags != "" %>
            <div class="panel-footer">
              <% story.all_tags.split(",").each do |tag| %>
                <span><%= link_to tag.strip, "/stories/sort?sort=tag&tag=#{tag.strip}", class: "btn btn-primary", role: "button" %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </a>
    <% end %>
  </div>
</section>

app/views/welcome/_footer.html.erb
<footer class="footer" style="background-color: black">
    <div class="container text-center">
        <div class="row copyright">
            <div class="col-lg-12">
                <p class="nexa-light center">&copy; <%= Time.current.year %> RDJ</p>
            </div>
        </div>
    </div>
</footer>

app/views/welcome/_guestbook.html.erb
<section id="guestbook">

  <div class="container text-center wow fadeIn">
    <h4>Guestbook</h4>
    <hr class="pageLine">
    <h6>Thanks for stopping by!</h6>
    <h6>We'd love it if you could leave a comment or memory of Don to share with us.</h6>

    <div class="row">
      <% if !@guestbook_comments.empty? %>
        <% @guestbook_comments.each do |comment| %>
          <div class="col-md-12">
            <br>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title text-left"><%= comment.author.name %> says:
                <span class="float-right"><%=time_ago_in_words(comment.created_at) %> ago</span>
                </h3>
              </div>
              <div class="panel-body text-left">
                <%= comment.content %>
                <% if logged_in? && current_user.id == comment.author.id || logged_in? && current_user.admin? %>
                  <div class="float-right">
                    <%= link_to "Delete", comment, method: :delete, class: "btn btn-danger",
                                                      data: { confirm: "Are you sure you want to delete your comment?" } %>
                  </div>  
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  
  <div class="col-lg-12">
    <div class="text-center">
      <% if !logged_in? %>
      <%= link_to "Please log in to comment", login_path, class: "btn btn-default btn-lg buttonDropShadow", role: "button" %>
      <% else %>
      <%= form_for [current_user, Comment.new] do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_area :content, placeholder: "Type comment here...", class: "comment-area", cols: "100", rows: "5" %><br/>
      <%= f.submit "Submit Comment", class: "btn btn-default btn-lg buttonDropShadow", "data-toggle" => "tooltip", "title" => "Click to submit your comment"  %>
      <% end %>
      <% end %>
    </div>
  </div>

  </div>
</section> 

app/views/welcome/_header.html.erb
<header id="page-top" class="mobile-full" style="background-color: black">
    <div class="container vert-center">
        <div class="row">
            <div class="col-md-12">
                <h1 id="typedIn"></h1>
            </div>
            <div class="col-md-12">
                <div>
                    <%= image_tag("rdjesseeLogo.png", alt: "Logo", class: "img-responsive", id: "rdjesseeSignature") %>
                </div>
                <div class="">
                    <a class="btn page-scroll" id="scrollDownBook" href="#intro"><i class="fa fa-book fa-2x"></i></a>
                </div>
            </div>
            <div class="col-md-12 center">
                
            </div>
        </div>  
    </div>
</header>

app/views/welcome/_intro.html.erb
<section id="intro">
  <div class="container-fluid">
    <div class="row text-center">
      <div class="col-md-12 wow fadeIn" data-wow-delay=".2s">
        <%= image_tag("donsmiles.jpg", alt: "Logo", class: "img-responsive pull-left", id: "donSmiles") %>
        <p class="droid-serif">Ralph 'Don' Jessee (September 13th, 1921 - April 3rd, 2016) was born in the mountains of southwestern Virginia. During the Great Depression his family moved to Kentucky. After two years at Lincoln Memorial University, he earned his engineering degree at University of Kentucky. He was hired by Westinghouse and after a stint in the army he returned to the Aviation Division at Lima, Ohio. He enjoyed his work designing control and protective devices and methods for aircraft electric power systems. He was granted 30 U.S. patents during his 49 year career. Meanwhile he took a wife and reared a family of four children. Late in life he moved to Louisiana to live with his daughter Catherine and her family. He enrolled in a life writing class at Catherine's insistence. Don wrote prodigiously for 10 years in spite of worsening macular degeneration, and has left a surprising legacy of stories, poems and letters. They are archived here for your perusal and enjoyment.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_obit.html.erb
<section class="testimonials bg-gray" id="rdj_obit">
    <div class="container-fluid wow fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="testimonials-carousel">
                    <!-- NOTE: You can add more items to the carousel, or remove items you don't need! -->
                    <!-- Testimonial Item 1 -->
                    <div class="item">
                        <div class="row">
                            <div class="col-md-6">
                                <%= image_tag("grandpa.jpg", alt: "Grandpa Sitting", class: "img-responsive center-block", id: "obitPic1") %>
                            </div>
                            <div class="col-md-6">
                                <p class="nexa-light">Ralph Donald Jessee, 94, joined our Lord and Savior on April 3, 2016. He was taken down by old age and cancer.</p>
                                <p class="nexa-light">Ralph Donald was born to I.W. “Ike” and Ivo Jessee on September 13, 1921, in Appalachia, Virginia. His grandparents were subsistence farmers, his father was a clerk with the Louisville and Nashville Railroad, and his mother was a schoolteacher. In the third grade his family moved with the Railroad to Pineville, Kentucky, where he played football with, and graduated from, Pineville High School. He attended Lincoln Memorial University, in Harrogate, Tennessee, for two years and then transferred to the University of Kentucky in Lexington. He graduated in 1943 with a B.Sc. in Electrical Engineering.</p>
                            </div>
                        </div>

                    </div>
                    <!-- Testimonial Item 2 -->
                    <div class="item">
                        <div class="row">
                            <div class="col-md-6">
                                <%= image_tag("stevedon.jpg", alt: "Grandpa, Grandma, Steve", class: "img-responsive center-block", id: "obitPic2") %>
                            </div>
                            <div class="col-md-6">
                                <p class="nexa-light">Setting aside a job offer from the Manhattan Project because the recruiters wouldn’t tell him what he would be doing, he accepted a position from Westinghouse Electric Corporation, which took him to what later became the Aero Space Division in Lima, Ohio. However, he was soon drafted into the U.S. Army Signal Corps. Shortly after boot camp he had surgery on his thyroid, was honorably discharged, and returned to his job in Lima. Young Engineer Jessee thrived in his work environment. He enjoyed the camaraderie and the technical challenges and quickly became a top engineer in the critical work of building innovative and reliable electrical systems for the nation’s military aircraft.</p>
                            </div>
                        </div>
                    </div>
                <!-- Testimonial Item 3 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("rdjnewspaperarticle2.jpg", alt: "Newspaper article", class: "img-responsive center-block", id: "obitPic3") %>
                        </div>
                        <div class="col-md-6">
                            <p class="nexa-light">Although he led innovation on a wide variety of projects, one core and persistent focus of his career was improving systems that used converters to make alternating electric current (AC) from direct current (DC) sources by switching the output terminal to the source in a unique way. His job was to develop elegant control schemes to prevent the degradation of the output quality. A tale he wrote after he retired describes the help he received from a master. After several days of trying to understand why a model of one of his elegant control scheme designs was not working as planned, he arrived home with the intention of relaxing and putting the problem out of mind. He sat back and listened to a sublime piano concerto by Mozart and was carried away. When he came back to earth, he found himself at work on the problem, but the tension was gone. He knew what caused the anomaly and modified the design.</p>
                        </div>
                    </div>
                </div>
                <!-- Testimonial Item 4 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("westinghouseaward.jpg", alt: "Westinghouse Award", class: "img-responsive center-block", id: "obitPic4") %>
                        </div>
                        <div class="col-md-6">
                            <p class="nexa-light">During his career, Ralph Donald’s work garnered thirty patents. At least four times he received an award for submitting the most meritorious patent disclosure of the year. Along with colleagues he received the George Westinghouse Signature Award of Excellence. Of all the awards received, he regarded the Engineering Achievement Award the most significant. That award recognized the importance and ingenuity of his invention of a system still called the "Jessee Circuit"; that controls the operation of an electric power converter that converted direct current to alternating current for use in airplanes. In its basic form the converter output voltage was subject to distortion by load changes and by variations in switching devices. Ralph Donald’s task was to take into account these corrupting variations and eliminate their influence. The ”Jessee Circuit” did the job. He loved his work, and his very productive career with Westinghouse and its successor firms lasted fifty-three years.</p>
                        </div>
                    </div>
                </div>
                <!-- Testimonial Item 5 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("donmarriage2.jpg", alt: "Don and Mary at their wedding", class: "img-responsive center-block", id: "obitPic5") %>
                        </div>
                        <div class="col-md-6">
                            <p class="nexa-light">A young local lass named Mary Elizabeth Werff, a clerk, caught the eye of Ralph Donald after he reported for work in Lima. He married her in 1947, initially found very modest housing (which they referred to as a shack), and soon started a family that quickly grew to four offspring: David Lawrence, Stephen Ross, Catherine Ann, and Susanna Marie. He provided well for, and guided well, his family, supporting their involvement in good schools, Market Street Presbyterian Church, Boy Scouts and Girl Scouts, the wider family, adventurous annual camping vacations, and eventually the colleges of their choice. He and Mary formed a strong team of wonderful parents, he with stern advice and wise counsel and she with a good ear, good advice, and compassion. That loving partnership came to an untimely end when Mary died of cancer in 1973. Ralph Donald stayed actively and lovingly involved with his children and his grandchildren, but the support of Mary was sorely missed.</p>
                        </div>
                    </div>
                </div>
                <!-- Testimonial Item 6 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("davedortdonstevecat.jpg", alt: "Don, Dorothy, David, Steve, Catherine", class: "img-responsive center-block", id: "obitPic6") %>
                        </div>
                        <div class="col-md-6">
                            <p class="nexa-light">Finding that his college sweetheart, Mardelle Jones, had been divorced, he convinced her to consider marriage. They tied a knot that came untied ten years later. A few years later he found himself in an improbable match with Dorothy Phillips, at the time 60 years old, which turned into a delightful marriage. Dorothy, never having been married, was quick to adopt Ralph Donald’s brood and they in turn were happy to welcome her into the family. She became the de facto communications and reunions director for the family, a role that was much appreciated. Ralph Donald was heartbroken when he lost her to cancer in 2005.</p>
                        </div>
                    </div>
                </div>
                <!-- Testimonial Item 7 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("donwine.jpg", alt: "Grandpa Drinking Wine", class: "img-responsive center-block", id: "obitPic7") %>
                        </div>
                        <div class="col-md-6">
                            <p class="nexa-light">His macular degeneration worsened and he found it very difficult to live on his own. His daughter Catherine and her husband Ghulam Sarwar invited him to live with them in Lafayette, Louisiana. He found new friends and found a writing teacher/encourager, Kim Graham, with the Life Writing Classes sponsored by the University of Louisiana and Lafayette General Hospital, who encouraged and guided the production of 200 stories based on experience in his life. The collection of these stories portrays in rich detail a rich life. They will be available on the web at RalphDonaldJessee.com.</p>
                        </div>
                    </div>
                </div>
                <!-- Testimonial Item 8 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("family.jpg", alt: "Family", class: "img-responsive center-block", id: "obitPic8") %>
                        </div>
                        <div class="col-md-6">
                            <p class="nexa-light">Ralph Donald was preceded in death by his parents; his sister Margaret Givens; his brother James Marion Jessee; his wives Mary Elizabeth Jessee, Mardelle Jessee, and Dorothy Jessee; and his daughter Susanna Jessee Murbach. He is survived by his daughter Catherine Jessee Sarwar; his sons David Lawrence Jessee and Stephen Ross Jessee; his grandchildren Alica Jessee, Benjamin Jessee, Matthew Jessee, Beau Jessee, Shawn Sarwar, Rachel Setliff, Emily Duncan, Andre Jessee, Ursula Jessee; his grandchildren Aidan Jessee, Keegin Jessee, Logan Jessee, Ava Setliffe, Jane Setliffe, Isaac Duncan, and Adalyn Duncan; niece Jayna Strunk; and nephews Richard Givens and Mike Jessee.</p>
                        </div>
                    </div>
                </div> 
                <!-- Testimonial Item 9 -->
                <div class="item">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("donsmiles.jpg", alt: "Grandpa smiling", class: "img-responsive center-block", id: "obitPic9") %>
                        </div>
                        <div class="col-md-6">
                        <p class="nexa-light">A memorial service will be held at Grace Presbyterian Church in Lafayette on Saturday, April 23, 2016 at 2:00. In lieu of flowers, friends and family might consider a contribution in his name to one of the following organizations:</p>

                        <ul class="nexa-light">
                          <li><a href="http://www.milesperret.org">Miles Perett Cancer Services in Lafayette</a></li>
                          <li><a href="http://www.limasymphony.com">Lima Symphony Orchestra</a></li>
                          <li><a href="http://www.scouting.org">Boy Scouts of America</a></li>
                          <li><a href="http://www.hospiceacadiana.com/">Hospice of Acadiana</a></li>
                          <li><a href="http://www.heritage.org">Heritage Foundation</a></li>
                        </ul>

                        <p class="nexa-light"> The ashes of Ralph Donald will be interred next his wife Dorothy at Memorial Gardens in Lima, Ohio at a later date.</p>
                        </div>
                    </div>
                </div>    
                </div>
            </div>
        </div>
    </div>
</section>

app/views/welcome/_parallax1.html.erb
<aside class="cta-quote" id="quote_1_container" style="background-image: url(<%= asset_path 'book.jpg' %>);">
    <div class="container-fluid wow fadeIn">
        <div class="row">
            <div class="col-md-6 col-md-offset-6" data-wow-delay=".6s">
                <span class="quote" id="quote_1">"It was painful to write about things, which had been embarrassing to me at the time they happened. But when I read what I had written, I realized it wasn’t about me, but about a little boy who lived a long time ago.</span><br><br><span class="quote" id="quote_1_2">Upon hearing my classmates read their stories I realized that their lives might not have been so different from mine. That gave me confidence to write my own stories."</span>
                <hr class="pageLine">
                <span class="quote" id="quote_1_author">From "Write? Me?" - R.D. Jessee</span>
            </div>
        </div>
    </div>
</aside>

app/views/welcome/_parallax2.html.erb
<aside class="cta-quote" id="quote-2-background-image" style="background-image: url(<%= asset_path 'blurred.jpg' %>);">
    <div class="container-fluid wow fadeIn">
        <div class="row">
            <div class="col-md-6" data-wow-delay=".6s">
            <span class="quote" id="quote_2">"Looking at old pictures I see things that are sort of familiar or perhaps ought to be. For instance here is one taken in the front or side yard of an old house. I see shades of gray in broad outline except for things that are familiar such as faces and certain shapes. I depend on the vision of others to identify for me other shapes. That’s how I determined that the picture was taken in the yard of an old house."
            </span>
            <hr class="pageLine">
            <span class="quote" id="quote_2_author">From "Old Pictures" - R.D. Jessee</span>
            </div>
        </div>
    </div>
</aside>

app/views/welcome/_parallax3.html.erb
<aside class="cta-quote" id="quote-3-background-image" style="background-image: url(<%= asset_path 'microphone.jpg' %>);">
    <div class="container-fluid wow fadeIn">
        <div class="row">
            <div class="col-md-6" data-wow-delay=".6s">
            <span class="quote" id="quote_3">"If I could speak to the child I would simply encourage him to learn to love to read. The child never learned to read well, so he was a slow reader and reading always took too long. He needed practice reading some really interesting short stories."
            </span>
            <hr class="pageLine">
            <span class="quote" id="quote_3_author">From "Thoughts of Childhood" - R.D. Jessee</span>
            </div>
        </div>
    </div>
</aside>

app/views/welcome/_pictures.html.erb
<section id="show_pictures">
  <div class="container-fluid text-center">
    <h4>Pictures</h4>
    <hr class="pageLine" />
    <div>
      <a href=" <%= pictures_path %> " class="btn btn-default btn-lg buttonDropShadow" id="picturesButton" role="button" data-toggle="tooltip" title="Click to see the full list of pictures">Full List</a>
    </div>
    <div class="row">
      <% @pictures.each do |picture| %>
        <a href="<%= picture_path(picture.id) %>" class="blog_links">
          <div class="col-lg-4 wow fadeIn">
            <div class="thumbnail box-shadow">
              <% if picture.picture.attached? %> <%= image_tag picture.picture.variant(resize: "500x500", auto_orient: true), alt: "Picture", class:
            "img-responsive center-picture" %> <% end %>
              <div class="caption text-center">
                <h5><%= picture.caption %></h5>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/_recordings.html.erb
<section id="show_recordings">
  <div class="container text-center wow fadeIn">
    <h4>Recordings</h4>
    <hr class="pageLine" />
    <div>
      <a href="<%= recordings_path %>" class="btn btn-default btn-lg buttonDropShadow" id="recordingsButton" role="button" data-toggle="tooltip" title="Click to see the full list of stories with recorded readings">Full List</a>
    </div>
    <%= render partial: 'recordings/show', locals: {full: false} %>
  </div>
</div>
</section>

app/views/welcome/_videos.html.erb
<section id="show_videos">
  <div class="container-fluid text-center">
    <!-- Flash Section -->
    <% if !flash.empty? %> <%= render 'shared/flash2' %> <% end %>
    <h4>Videos</h4>
    <hr class="pageLine" />
    <h6>Here is a random sample of videos</h6>
    <div>
      <a href=" <%= videos_path %> " class="btn btn-default btn-lg buttonDropShadow" id="videosButton" role="button">Or check out all the videos</a>
    </div>
    <div class="row">
      <% @videos.each do |video| %>
        <a href="<%= video_path(video.id) %>" class="blog_links">
          <div class="col-lg-4 wow fadeIn">
            <div class="thumbnail box-shadow">
              <% if video.video_file.attached? %> <%= image_tag video.video_file, alt: "Video", class: "img-responsive center-picture" %> <% end %>
              <div class="caption text-center">
                <h5><%= video.caption %></h5>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/about.html.erb
<% provide(:title, 'About') %>
<h1>About RD Jessee's Blog</h1>
<h2>Ralph "Don" Jessee is my grandfather. My name is Andre. I decided to build a website to showcase his
stories.</h2>
<h2>But the real work in collecting these stories and making them accessible was done by my dad, David.</h2>

app/views/welcome/welcome.html.erb
<!-- Header -->
<%= render 'header' %>

<!-- Flash Section -->
<% if !flash.empty? %>
    <%= render 'shared/flash' %>
<% end %>

<!-- Intro -->
<%= render 'intro' %>

<!-- Parallax 1 -->
<%= render 'parallax1' %>

<!-- Blog -->
<%= render 'blog' %>

<!-- Parallax 2 -->
<%= render 'parallax2' %>

<!-- Pictures -->
<%= render 'pictures' %>

<!-- Parallax 3 -->
<%= render 'parallax3' %>

<!-- Recordings -->
<%= render 'recordings' %>

<!-- Obituary -->
<%= render 'obit' %>

<!-- Guest Book -->
<%= render 'guestbook' %>

<!-- Eventually we want to render 'videos' here Videos -->

<!-- Footer -->
<%= render 'footer' %>