config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#welcome'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'welcome' => 'welcome#welcome'
  get 'about' => 'welcome#about'
  get 'signup' => 'users#new'
  get 'blog' => 'stories#index'
  get 'tag_cloud' => 'tags#show'

  post 'email_responses/bounce' => 'email_responses#bounce'
  post 'email_responses/complaint' => 'email_responses#complaint'

  get '/admin',   to: 'admin_pages#main'
  get '/admin/users',   to: 'admin_pages#admin_users'
  get '/admin/stories',   to: 'admin_pages#admin_stories'

  get 'stories/sort' => 'stories#sort'
  get 'stories/search' => 'stories#search'

  resources :users do
    resources :stories
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :stories do
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :comments do
    resources :comments
  end

  resources :pictures do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :recordings do
    resources :comments
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def main
    @user = current_user
  end

  def admin_users
    @users = User.all.order(:id).paginate(page: params[:page])
  end

  def admin_stories
    if params[:sort_info]
      query_string = "#{params[:sort_info][:sort_using]} #{params[:sort_info][:opposite_direction]}"
      @sortInfo = {"#{params[:sort_info][:sort_using]}": {direction: params[:sort_info][:opposite_direction], opposite_direction: params[:sort_info][:direction], icon_class: helpers.get_sort_icon_class(params[:sort_info][:sort_using], params[:sort_info][:opposite_direction])}}
    else
      query_string = "title ASC"
      @sortInfo = {"title": {direction: "ASC", opposite_direction: "DESC", icon_class: helpers.get_sort_icon_class("title", "ASC")}}
    end
    @stories = Story.all.order(query_string).paginate(page: params[:page])
  end

  private

    #before filters
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/views/admin_pages/admin_stories.html.erb
<section id="admin_stories">
  <div class="container-fluid text-center">
    <h1>Stories</h1>
    <p>You can click into fields to edit values. You will see the cell turn green if you have sucessfully updated it.</p>
    <%= will_paginate @stories %>
    <table class="table table-bordered">
      <tr>
        <th class="text-center">ID 
          <% sort_link_hash = create_sort_link_hash(@sortInfo, "id") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
        </th>
        <th class="text-center">Title
          <% sort_link_hash = create_sort_link_hash(@sortInfo, "title") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
        </th>
        <th class="text-center">Year Written
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "year_written") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Decade
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "decade") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Location
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "location") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Genre
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "genre") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Category
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "category") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Life Stage
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "life_stage") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Word Count
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "word_count") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %></th>
        <th class="text-center">Delete</th>
        <th class="text-center">Date Created
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "created_at") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
        <th class="text-center">Date Updated
        <% sort_link_hash = create_sort_link_hash(@sortInfo, "updated_at") %>
         <%= link_to admin_stories_path(sort_link_hash[:params]) do %>  
            <i class="<%= sort_link_hash[:icon_class] %>"></i>
          <% end %>
          </th>
      </tr>
      <% @stories.each do |story| %>
        <tr>
          <td><%= story.id %></td>
          <td><%= link_to story.title, story %></td>
          <td contenteditable='true' storyID='<%= story.id %>' selectString="yes" attributeToUpdate='year_written'>
            <%= form_for(story) do |f| %>
              <%= f.select :year_written, options_for_select((2004..2017).to_a.unshift("None").map {|s| ["#{s}", s]}, story.year_written), class: 'form-control' %>
            <% end %>
          </td>
          <td contenteditable='true' storyID='<%= story.id %>' selectInteger="yes" attributeToUpdate='decade'>
            <%= form_for(story) do |f| %>
              <%= f.select :decade, options_for_select((1..9).to_a.unshift("None").map {|s| ["#{s}", s]}, story.decade), class: 'form-control' %>
            <% end %>
          </td>
          <td contenteditable='true' storyID='<%= story.id %>' fillIn="yes" attributeToUpdate='location'><%= story.location %></td>
          <td contenteditable='true' storyID='<%= story.id %>' selectString="yes" attributeToUpdate='genre'>
            <%= form_for(story) do |f| %>
              <%= f.select :genre, options_for_select([['None', nil], ['Fiction','Fiction'],['Non-Fiction','Non-Fiction']], if story.genre != nil then story.genre else "None" end), class: 'form-control' %>
            <% end %>
          </td>
          <td contenteditable='true' storyID='<%= story.id %>' selectString="yes" attributeToUpdate='category'>
            <%= form_for(story) do |f| %>
              <%= f.select :category, options_for_select([['None', nil], ['Story','Story'],['Poem','Poem'], ['Letter','Letter']], if story.category != nil then story.category else "None" end), class: 'form-control' %>
            <% end %>
          </td>
          <td contenteditable='true' storyID='<%= story.id %>' selectString="yes" attributeToUpdate='life_stage'>
            <%= form_for(story) do |f| %>
              <%= f.select :life_stage, options_for_select([['None', nil], ['Early','Early'],['Middle','Middle'], ['Late','Late']], if story.life_stage != nil then story.life_stage else "None" end ), class: 'form-control' %>
            <% end %>
          </td>
          <td storyID='<%= story.id %>'><%= story.word_count %></td>
          <td><%= link_to "Delete", story, method: :delete, class: "btn btn-danger",
                                  data: { confirm: "This story took a while to write. Are you sure?" } %></td>
          <td><%= time_ago_in_words(story.created_at) %> ago</td>
          <td><%= time_ago_in_words(story.updated_at) %> ago</td>
        </tr>
      <% end %>
    </table>
  </div>
</section>

app/views/admin_pages/admin_users.html.erb
<section id="admin_users">

  <div class="container-fluid text-center">

    <h1>Users</h1>
    <p>You can make users admins and activate their accounts from this page. You will see the cell turn green if you have sucessfully updated it.</p>
    <%= will_paginate @users%>
    <table class="table table-bordered">
      <tr>
        <th class="text-center">ID</th>
        <th class="text-center">Name</th>
        <th class="text-center">Email</th>
        <th class="text-center">Admin?</th>
        <th class="text-center">Activated?</th>
        <th class="text-center">Delete</th>
        <th class="text-center">Date Created</th>
        <th class="text-center">Date Updated</th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td contenteditable='true' userID='<%= user.id %>' attributeToUpdate='admin'>
          <select name="value" id="tellMe<%= user.id %>">
            <option value="1" <%= "selected" if user.admin? %> >True</option>
            <option value="0" <%= "selected" if !user.admin? %> >False</option>
          </select>
        </td>
        <td contenteditable='true' userID='<%= user.id %>' attributeToUpdate='activated'>
          <select name="value" id="tellMe<%= user.id %>">
            <option value="1" <%= "selected" if user.activated? %> >True</option>
            <option value="0" <%= "selected" if !user.activated? %> >False</option>
          </select>
        </td>
          <td><%= link_to "Delete", user, method: :delete, class: "btn btn-danger",
                                  data: { confirm: "There is no good reason for you to be deleting users. Are you sure?" } %></td>
          <td><%= time_ago_in_words(user.created_at)%> ago</td>
          <td><%= time_ago_in_words(user.updated_at)%> ago</td>
        </tr>
        <% end %>
      </table>

    </div>

  </section>

app/views/admin_pages/main.html.erb
<section id="admin_panel">
<% provide(:title, @user.name) %>
<div>

</div>
<div class="row">
  <div class="col-md-12">
  <%= gravatar_for @user %>
  <h4>Hi <%= @user.name %>. This is your admin panel.</h4>
    <%= link_to 'Users', admin_users_path, class: "btn btn-default", role: "button" %>
    <%= link_to 'Stories', admin_stories_path, class: "btn btn-default", role: "button" %>
  </div>
</div>
</section>