config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#welcome'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'welcome' => 'welcome#welcome'
  get 'about' => 'welcome#about'
  get 'signup' => 'users#new'
  get 'blog' => 'stories#index'
  get 'tag_cloud' => 'tags#show'

  post 'email_responses/bounce' => 'email_responses#bounce'
  post 'email_responses/complaint' => 'email_responses#complaint'

  get '/admin',   to: 'admin_pages#main'
  get '/admin/users',   to: 'admin_pages#admin_users'
  get '/admin/stories',   to: 'admin_pages#admin_stories'

  get 'stories/sort' => 'stories#sort'
  get 'stories/search' => 'stories#search'

  resources :users do
    resources :stories
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :stories do
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :comments do
    resources :comments
  end

  resources :pictures do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :recordings do
    resources :comments
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy
  has_many :pictures, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :recordings, as: :recordable, dependent: :destroy
  accepts_nested_attributes_for :recordings, allow_destroy: true
  has_many :videos, as: :videoable, dependent: :destroy
  accepts_nested_attributes_for :videos, allow_destroy: true
  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true
  has_one_attached :picture

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def self.search(query)

    search_definition = {
      from: 0,
      size: 500,
      query: {
        multi_match: {
          query: query,
          fields: ['title', 'content']
        }
      },
      highlight: {
        pre_tags: ['<mark>'],
        post_tags: ['</mark>'],
        fields: {
          title: {number_of_fragments: 0},
          content: {},
        }
      },
      suggest: {
        text: query,
        title: {
          term: {
            size: 1,
            field: :title
          }
        },
        content: {
          term: {
            size: 1,
            field: :content
          }
        }
      }
    }

    if (query[0] == '"' || query[0] == "'") && (query[-1] == '"' || query[-1] == "'")
      search_definition[:query][:multi_match][:type] = 'phrase'
      search_definition.delete(:suggest)
    end
    __elasticsearch__.search(search_definition)
  end

  def as_indexed_json(options = nil)
    self.as_json( only: [ :title, :content ] )
  end

  @@year_array = []
  @@decade_array = []
  @@location_array = []
  @@genre_array = []
  @@category_array = []
  @@life_stage_array = []

  def self.get_metadata
    Story.find_each do |story|
      @@year_array.push(story.year_written)
      @@decade_array.push(story.decade)
      @@location_array.push(story.location) if story.location != nil
      @@genre_array.push(story.genre) if story.genre != nil
      @@category_array.push(story.category) if story.category != nil
      @@life_stage_array.push(story.life_stage) if story.life_stage != nil
    end
  end

  def self.get_stories(page)
    Story.all.order(title: :asc).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_year(year, page)
    Story.where(year_written: year.to_i).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_decade(decade, page)
    Story.where(decade: decade.to_i).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_location(location, page)
    Story.where(location: location).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_genre(genre, page)
    Story.where(genre: genre).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_category(category, page)
    Story.where(category: category).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_life_stage(life_stage, page)
    Story.where(life_stage: life_stage).paginate(:page => page, :per_page => 6)
  end

  def self.get_stories_with_recordings(page)
    Story.joins(:recordings).order(title: :asc).paginate(:page => page, :per_page => 6)
  end

  def self.get_stories_with_comments(page)
    Story.joins(:comments).paginate(:page => page, :per_page => 6)
  end

  def self.order_by_tag(tag, page)
    Tag.find_by_name!(tag.strip).stories.paginate(:page => page, :per_page => 6)
  end

  def self.all_years
    @@year_array.compact!
    @@year_array.sort.uniq!
  end

  def self.all_decades
    @@decade_array.compact!
    @@decade_array.sort.uniq!
  end

  def self.all_locations
    @@location_array.compact!
    @@location_array.sort.uniq!
  end

  def self.all_genres
    @@genre_array.compact!
    @@genre_array.sort.uniq!
  end

  def self.all_categories
    @@category_array.compact!
    @@category_array.sort.uniq!
  end

  def self.all_life_stages
    @@life_stage_array.compact!
    @@life_stage_array = @@life_stage_array.sort.uniq!
    @@life_stage_array[1], @@life_stage_array[2] = @@life_stage_array[2], @@life_stage_array[1] 
    @@life_stage_array
  end

  def strip_divs
    self.title.gsub!("<div>", "")
    self.title.gsub!("</div>", "")
    self.content.gsub!("<div>", "")
    self.content.gsub!("</div>", "")
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def get_wordcount
    self.word_count = self.content.scan(/[\w-]+/).size
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :new, :edit]
  before_action :admin_user,   only: [:destroy, :edit]

  def new
    @story = Story.new
    @recordings = @story.recordings.new
  end

  def index
    @stories = Story.get_stories(params[:page])
    @active_button = "alphabetical"
    Story.get_metadata
    @years = Story.all_years
    @decades = Story.all_decades
    @locations = Story.all_locations
    @genres = Story.all_genres
    @categories = Story.all_categories
    @life_stages = Story.all_life_stages
  end

  def sort
    Story.get_metadata
    @years = Story.all_years
    @decades = Story.all_decades
    @locations = Story.all_locations
    @genres = Story.all_genres
    @categories = Story.all_categories
    @life_stages = Story.all_life_stages
    case params[:sort]
    when "year_written"
      @active_button = "year"
      @stories = Story.order_by_year(params[:year], params[:page])
      render 'index'
    when "decade"
      @active_button = "decade"
      @stories = Story.order_by_decade(params[:decade], params[:page])
      render 'index'
    when "location"
      @active_button = "location"
      @stories = Story.order_by_location(params[:location] , params[:page])
      render 'index'
    when "genre"
      @active_button = "genre"
      @stories = Story.order_by_genre(params[:genre] , params[:page])
      render 'index'
    when "category"
      @active_button = "category"
      @stories = Story.order_by_category(params[:category] , params[:page])
      render 'index'
    when "life_stage"
      @active_button = "life_stage"
      @stories = Story.order_by_life_stage(params[:life_stage] , params[:page])
      render 'index'
    when "has_recordings"
      @active_button = "has_recordings"
      @stories = Story.get_stories_with_recordings( params[:page])
      render 'index'
    when "has_comments"
      @active_button = "has_comments"
      @stories = Story.get_stories_with_comments( params[:page])
      render 'index'
    when "tag"
      @active_button = "tag"
      @stories = Story.order_by_tag(params[:tag] , params[:page])
      render 'index'
    end
  end

  def search
    Story.get_metadata
    @years = Story.all_years
    @decades = Story.all_decades
    @locations = Story.all_locations
    @genres = Story.all_genres
    @categories = Story.all_categories
    @life_stages = Story.all_life_stages
    story_ids = []
    @results = Story.search(search_params[:query])
    @results.each do |result|
      story_ids.push(result.id)
    end
    @stories = Story.where(id: story_ids).paginate(:page => params[:page], :per_page => 6)
    render 'index'
  end

  def show
    @story = Story.find(params[:id])
  end

  def edit
    @story = Story.find(params[:id])
    @all_tags = Tag.all
  end

  def update
    if request.xhr?
      @story = Story.find(params[:id])
      params[:attributeValue] = nil if params[:attributeValue] == ""
      if @story[params[:attributeToUpdate]].to_s != params[:attributeValue]
        if @story.update_attributes(params[:attributeToUpdate] => params[:attributeValue])
          @story.strip_divs
          @story.get_wordcount
          @story.save
          @value = @story[params[:attributeToUpdate]]
          render plain: "Change"
        end
      end
    else
      @story = Story.find(params[:id])
      helpers.clean_story_params(story_params, params)
      if @story.update_attributes(story_params)
        @story.strip_divs
        @story.get_wordcount
        @story.save
        flash[:success] = "Story updated"
        redirect_to @story
      else
        render 'edit'
      end 
    end

  end

  def create
    helpers.clean_story_params(story_params, params)
    @story = current_user.stories.build(story_params)
    @story.strip_divs
    @story.get_wordcount
    if @story.save
      flash.now[:success] = "Story created!"
      render :show
    else
      flash.now[:info] = "Oops, that didn't work"
      redirect_to "/#flash"
    end
  end

  def destroy
    @story = Story.find(delete_params)
    @story.destroy
    flash.now[:success] = "Story deleted"
    redirect_to request.referrer || root_url
  end

  private

  def story_params
    params.require(:story).permit(:title, :content, :year_written, :decade, :location, :genre, :category, :life_stage, :picture, :all_tags, recordings_attributes: [:caption, :audio_file] )
  end

  def search_params
    params.permit(:query, :commit)
  end

  def delete_params
    params.require(:id)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_user
    @story = current_user.stories.find_by(id: params[:id])
    redirect_to root_url if @story.nil?
  end

end

app/helpers/stories_helper.rb
# frozen_string_literal: true

module StoriesHelper
  def tag_links(tags)
    tags.split(',').map { |tag| link_to tag.strip, tag_path(tag.strip) }.join(', ')
  end

  def tag_cloud(tags, classes)
    max = tags.max_by(&:count)
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

  def autosuggest_aggregate(response, fields, query)
    # Stores unique words and their autocorrect suggestions
    words = {}

    # Iterate over fields
    fields.each do |field|
      # Iterate over query words
      response.send(field).to_a.each do |word|
        # If any options are available
        next if word.options.empty?

        # Append word if it doesn't already exist
        new_word = false
        unless words.include? word.text
          words[word.text] = { text: '', score: nil, freq: nil }
          new_word = true
        end
        word.options.each do |option|
          unless new_word || (words[word.text][:score] * words[word.text][:freq] < option[:score] * option[:freq])
            next
          end

          words[word.text][:text] = option[:text]
          words[word.text][:score] = option[:score]
          words[word.text][:freq] = option[:freq]
        end
      end
    end

    new_query = query.dup

    # Generate a new string based on the high score suggestions
    words.each do |word, suggestion|
      new_query[word] = suggestion[:text] if suggestion[:score] > 0.65
    end

    # Return the new query or false if there were no modifications
    return new_query unless new_query == query

    false
  end

  def pluralize_without_count(count, noun, text = nil)
    if count != 0
      count == 1 ? "#{noun}#{text}" : "#{noun.pluralize}#{text}"
    end
  end

  def get_results(results, story)
    if results
      results = results.select { |r| r.id == story.id.to_s }.first
      title = results.highlight.title_searchable.nil? ? story.title.body.to_html : results.highlight.title_searchable.first
      content = results.highlight.content_searchable.nil? ? Truncato.truncate(story.content.body.to_html, max_length: 400) : results.highlight.content_searchable.join(' / ').html_safe
    else
      title = story.title
      content = Truncato.truncate(story.content.body.to_html, max_length: 400)
    end
    {
      title: title,
      content: content
    }
  end

  def get_results_query(results)
    results.search.definition[:body][:query][:multi_match][:query]
  end

  def clean_story_params(story_params, params)
    if story_params[:year_written] == 'None'
      params[:story].delete(:year_written)
    end
    params[:story].delete(:decade) if story_params[:decade] == 'None'
    params[:story].delete(:genre) if story_params[:genre] == ''
    params[:story].delete(:location) if story_params[:location] == ''
    params[:story].delete(:category) if story_params[:category] == ''
    params[:story].delete(:life_stage) if story_params[:life_stage] == ''
    unless nested_hash_value(story_params[:recordings_attributes].to_h, :audio_file)
      params[:story].delete(:recordings_attributes)
    end
  end

  def nested_hash_value(obj, key)
    if obj.respond_to?(:key?) && obj.key?(key)
      obj[key]
    elsif obj.respond_to?(:each)
      r = nil
      obj.find { |*a| r = nested_hash_value(a.last, key) }
      r
    end
  end

  def create_sort_link_hash(sort_info_obj, sort_by_string)
    if sort_info_obj.keys.first == sort_by_string.to_sym
      @title = sort_by_string
      @direction = sort_info_obj[sort_by_string.to_sym][:direction]
      @opposite_direction = sort_info_obj[sort_by_string.to_sym][:opposite_direction]
      @icon_class = get_sort_icon_class(@title, @direction)
    else
      @title = sort_by_string
      @direction = 'DESC'
      @opposite_direction = 'ASC'
      @icon_class = get_sort_icon_class(@title, @direction)
    end
    @params = { params: {sort_info: { sort_using: @title, direction: @direction, opposite_direction: @opposite_direction }}, icon_class: @icon_class }
  end

  def get_sort_icon_class(sort_by_string, direction)
    case sort_by_string
    when 'id', 'year_written', 'decade', 'word_count', 'created_at', 'updated_at'
      if direction == 'ASC'
        @icon_class = "fas fa-sort-numeric-down-alt"
      elsif direction == 'DESC'
        @icon_class = "fas fa-sort-numeric-up"
      end
    when 'title', 'location', 'genre', 'category', 'life_stage'
      if direction == 'ASC'
        @icon_class = "fas fa-sort-alpha-down-alt"
      elsif direction == 'DESC'
        @icon_class = "fas fa-sort-alpha-up"
      end
    end
    @icon_class
  end
end

app/views/stories/_failure.html.erb
<p>Thats a fail</p>

app/views/stories/_show.html.erb
<section id="blog_full">
  <!-- Flash Section -->
  <% if !flash.empty? %> <%= render 'shared/flash' %> <% end %>
  <div class="container-fluid text-center">
    <div>
      <p>
        <%= link_to 'Most Recent', "/stories/sort?sort=alphabetical", class: "btn btn-primary", role: "button" %>
      </p>
      <button type="button" class="btn btn-primary active">Primary</button>
    </div>
    <%= will_paginate @stories %>
    <div class="row">
      <% @stories.each do |story| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <% if story.picture.attached? %> <%= image_tag story.picture, alt: "Thumbnail", class: "img-responsive center-picture" %> <% end %>
            <div class="caption">
              <h3><%= story.title.html_safe %></h3>
              <p>
                <%= truncate(story.content.html_safe, length: 125, omission: '...(click to continue reading)') %>
              </p>
              <p>
                <a href=" <%= story_path(story.id) %> " class="btn btn-primary" role="button">Read</a>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/stories/_show_stories.html.erb
<div id="stories_container">
  <% if @active_button != 'alphabetical' || @results %>
    <div class="row">
      <div class="col-sm-6 col-md-6 col-md-offset-3 top-margin-5-percent">
        <div class="alert alert-info" role="alert">
          <% if @active_button == "tag" %>
            <h6>
              There <%= @stories.count > 1 ? "are" : "is" %> <%= pluralize(@stories.count, "story") %> with that <%= @active_button %>
            </h6>
          <% elsif @active_button == "genre" %>
            <h6>
              There <%= @stories.count > 1 ? "are" : "is" %> <%= pluralize(@stories.count, "story") %> in that <%= @active_button %>
            </h6>
          <% elsif @active_button == "life_stage" %>
            <h6>
              There <%= @stories.count > 1 ? "are" : "is" %> <%= pluralize(@stories.count, "story") %> from that life stage
            </h6>
          <% elsif @active_button == "has_recordings" %>
            <h6>
              There <%= @stories.count > 1 ? "are" : "is" %> <%= pluralize(@stories.count, "story") %> that have audio <%= pluralize_without_count(@stories.count, "recording") %>
            </h6>
          <% elsif @active_button == "has_comments" %>
            <h6>
              There <%= @stories.count > 1 ? "are" : "is" %> <%= pluralize(@stories.count, "story") %> that <%= @stories.count > 1 ? "have" : "has" %> comments
            </h6>
          <% elsif @results %>
            <% if @results.count == 0 %>
              <h6>
                No results found that contain '<%= get_results_query(@results) %>'
                <% if @results.response.suggest %>
                  <% suggestion = autosuggest_aggregate(@results.response.suggest, [:title, :body], get_results_query(@results)) %>
                  <% if suggestion %>
                    Search instead for: <%=  link_to suggestion, stories_search_path( query: suggestion ) %>
                  <% end %>
                <% end %>
              </h6>
            <% else %>
              <h6>
                There <%= @results.count > 1 ? "are" : "is" %> <%= pluralize(@results.count, "story") %> that <%= @results.count > 1 ? "match" : "matches" %> '<%= @results.search.definition[:body][:query][:multi_match][:query] %>'
              </h6>
            <% end %>
          <% else %>
            <h6>
              There <%= @stories.count > 1 ? "are" : "is" %> <%= pluralize(@stories.count, "story") %> from that <%= @active_button %>
            </h6>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div>
    <%= will_paginate @stories if @stories %>
  </div>
  <% if @stories %>
    <% @stories.each do |story| %>
      <% result_hash = get_results(@results, story) %>
      <a href="<%= story_path(story.id) %>" class="blog_links" >
        <div class="row panel panel-default box-shadow">
          <div class="panel-body">
            <% if story.picture.attached? %>
              <div class="col-md-5">
                <div>
                  <%= image_tag story.picture, alt: "Thumbnail", class: "img-responsive center-picture" %>
                </div>
              </div>
              <div class="col-md-7">
                <div class="caption black">
                  <h3 class="MajestiBannerBookPartial">
                    <%= raw result_hash[:title] %>
                  </h3>
                  <div class="MajestiBannerBookParaPartial text-left">
                    <%= raw result_hash[:content] %>
                  </div>
                </div>
                <% if story.recordings.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has an audio recording"><i class="far fa-file-audio fa-2x"></i></div>
                <% end %>
                <% if story.comments.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has comments"><i class="far fa-comments fa-2x"></i></div>
                <% end %>
              </div>
            <% else %>
              <div class="col-md-12">
                <div class="caption black">
                  <h3 class="MajestiBannerBookPartial">
                    <%= raw result_hash[:title] %>
                  </h3>
                  <div class="MajestiBannerBookParaPartial text-left">
                    <%= raw result_hash[:content] %>
                  </div>
                </div>
                <% if story.recordings.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has an audio recording"><i class="far fa-file-audio fa-2x"></i></div>
                <% end %>
                <% if story.comments.length > 0 %>
                  <div class="text-left" data-toggle="tooltip" title="This story has comments"><i class="far fa-comments fa-2x"></i></div>
                <% end %>
              </div>
            <% end %>
            <% if story.word_count != nil %>
              <div class="col-md-12">
                <div class="float-right black">
                  <p class="MajestiBannerBookPartial">
                    Estimated Reading Time: <% if (story.word_count / 130.0) > 1 %> <%= (story.word_count / 130.0).round(1) %> minutes <% else %> 1 minute <% end %>
                  </p>
                </div>
              </div>
            <% end %>
          </div>
          <% if story.all_tags != "" %>
            <div class="panel-footer">
              <% story.all_tags.split(",").each do |tag| %>
                <span><%= link_to tag.strip, "/stories/sort?sort=tag&tag=#{tag.strip}", class: "btn btn-primary", role: "button" %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </a>
    <% end %>
  <% end %>
  <div>
    <%= will_paginate @stories if @stories %>
  </div>
</div>

app/views/stories/_story.html.erb
<li id="story-<%= story.id %>">
  <%= link_to gravatar_for(story.user, size: 50), story.user %>
  <span class="user"><%= link_to story.user.name, story.user %></span>
  <span class="title"><%= story.title %></span>
  <span class="content"><%= story.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(story.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/stories/_sucess.html.erb
<p>That worked!</p>

app/views/stories/_tag_cloud.html.erb
<div class="tags-cloud">
  <h4>Tags Cloud</h4>
  <% tag_cloud Tag.counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.id), class: css_class %>
  <% end %>
</div>

app/views/stories/index.html.erb
<section id="blog_full">
  <!-- Flash Section -->
  <% if !flash.empty? %>
    <%= render 'shared/flash' %>
  <% end %>
  <div class="container text-center">
    <div id="elastic-search-bar" class="form">
      <%= form_with(url: stories_search_path, method: "get", local: true, class: "form-inline") do |f| %>
        <%= f.text_field :query, placeholder: "Word or phrase", required: true, class: "form-control" %>
        <%= f.submit :Search, class: "btn btn-primary mb-2" %>
      <% end %>
    </div>
    <div class="btn-group">
      <%= link_to 'Alphabetical', stories_path, id: "alpha_button", class: "#{'active' if @active_button == 'alphabetical' } btn btn-default", role: "button" %>
      <% if !@years.nil? %>
        <div class="btn-group">
          <button type="button" id="year_button" class="<%= 'active' if @active_button == 'year' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Year Written <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @years.each do |year| %>
              <li><%= link_to year, "/stories/sort?sort=year_written&year=#{year}", class: "btn", role: "button" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if !@decades.nil? %>
        <div class="btn-group">
          <button type="button" id="decade_button" class="<%= 'active' if @active_button == 'decade' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Decade <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @decades.each do |decade| %>
              <li><%= link_to decade, "/stories/sort?sort=decade&decade=#{decade}", class: "btn", role: "button" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if !@locations.nil? %>
        <div class="btn-group">
          <button type="button" id="location_button" class="<%= 'active' if @active_button == 'location' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Location <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @locations.each do |location| %>
              <li><%= link_to location, "/stories/sort?sort=location&location=#{location}", class: "btn", role: "button" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if !@genres.nil? %>
        <div class="btn-group">
          <button type="button" id="genre_button" class="<%= 'active' if @active_button == 'genre' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Genre <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @genres.each do |genre| %>
              <li><%= link_to genre, "/stories/sort?sort=genre&genre=#{genre}", class: "btn", role: "button" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if !@categories.nil? %>
        <div class="btn-group">
          <button type="button" id="type_button" class="<%= 'active' if @active_button == 'category' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @categories.each do |category| %>
              <li><%= link_to category, "/stories/sort?sort=category&category=#{category}", class: "btn", role: "button" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% if !@life_stages.nil? %>
        <div class="btn-group">
          <button type="button" id="age_button" class="<%= 'active' if @active_button == 'life_stage' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Life Stage <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @life_stages.each do |life_stage| %>
              <li><%= link_to life_stage, "/stories/sort?sort=life_stage&life_stage=#{life_stage}", class: "btn", role: "button" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= link_to 'Audio', "/stories/sort?sort=has_recordings", id: "recordings_button", class: "#{'active' if @active_button == 'has_recordings' } btn btn-default", role: "button" %>
      <%= link_to 'Comments', "/stories/sort?sort=has_comments", id: "comments_button", class: "#{'active' if @active_button == 'has_comments' } btn btn-default", role: "button" %>
      <div class="btn-group">
        <button type="button" id="tags_button" class="<%= 'active' if @active_button == 'tag' %> btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Tags <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to 'Tag Cloud', tag_cloud_path, id: "tag-cloud", class: "btn tag-xhr-request", role: "button" %></li>
          <li><%= link_to 'Tag List', tags_path, id: "tag-list", class: "btn tag-xhr-request", role: "button" %></li>
        </ul>
      </div>
      
    </div>
    <%= render partial: 'show_stories', locals: {results: @results} %>
  </div>
</section>
 

app/views/stories/update.html.erb
<h1>STuff</h1>