config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'welcome#welcome'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'welcome' => 'welcome#welcome'
  get 'about' => 'welcome#about'
  get 'signup' => 'users#new'
  get 'blog' => 'stories#index'
  get 'tag_cloud' => 'tags#show'

  post 'email_responses/bounce' => 'email_responses#bounce'
  post 'email_responses/complaint' => 'email_responses#complaint'

  get '/admin',   to: 'admin_pages#main'
  get '/admin/users',   to: 'admin_pages#admin_users'
  get '/admin/stories',   to: 'admin_pages#admin_stories'

  get 'stories/sort' => 'stories#sort'
  get 'stories/search' => 'stories#search'

  resources :users do
    resources :stories
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :stories do
    resources :comments
    resources :pictures
    resources :videos
    resources :recordings
  end

  resources :comments do
    resources :comments
  end

  resources :pictures do
    resources :comments
  end

  resources :videos do
    resources :comments
  end

  resources :recordings do
    resources :comments
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :tags
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :photographer, class_name: 'User', foreign_key: :user_id
  belongs_to :imageable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :taggings
  has_many :tags, through: :taggings
  has_one_attached :picture

  def strip_divs
    self.caption.gsub!("<div>", "")
    self.caption.gsub!("</div>", "")
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :new, :edit]
  before_action :correct_user,   only: [:destroy, :edit]

  def new
    @picture = current_user.pictures.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    @picture.strip_divs
    if @picture.save
      flash.now[:success] = "Picture uploaded successfully!"
      render :show
    else
      render 'new'
    end
  end

  def index
    @pictures = Picture.all.order(created_at: :asc).paginate(:page => params[:page], :per_page => 3)
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(picture_params)
      @picture.strip_divs
      @picture.save
      flash[:success] = "Picture updated"
      redirect_to @picture
    else
      render 'edit'
    end 
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:success] = "Picture deleted"
    redirect_to request.referrer || root_url
  end

  private

  def picture_params
    params.require(:picture).permit(:caption, :picture, :user_id)
  end

  def correct_user
    @picture = Picture.find_by(id: params[:id])
    redirect_to(root_url) unless @picture.user_id == current_user.id || current_user.admin?
  end

end

app/views/pictures/edit.html.erb
<section id="picture_edit">
    <div class="container-fluid">

      <div class="row">
        <div class="col-lg-12 text-center">
          <h4>Edit Picture</h4>
          <hr class="pageLine">
        </div>
      </div>

        <div class="row">
            <div class="col-lg-12 wow fadeIn">
            <%= form_for(@picture) do |f| %>
              <%= render 'shared/error_messages', object: f.object %>
                <%= f.hidden_field :user_id, value: current_user.id %>
              <div>
                <%= f.label :caption %>
                <%= f.trix_editor :caption, class: 'form-control', placeholder: @picture.caption %>
              </div>
              <div>
                <h5>If you want to change this picture:</h5>
                 <% if @picture.picture.attached? %>
                  <%= image_tag @picture.picture.variant(resize: "800x800", auto_orient: true), alt: "Picture", class: "img-responsive center-picture" %>
                 <% end %>
                <h5>Upload a new one below</h5>
              </div>
              <div class="picture">
                <%= f.label "Upload picture" %>
                <%= f.file_field :url %>
              </div>
              <br>
              <div class="text-center">
                <%= f.submit "Update Picture", class: "btn btn-default btn-lg buttonDropShadow" %>
              </div>
            <% end %>
            </div>
        </div>
    </div>
</section> 

app/views/pictures/index.html.erb
<section id="pictures_full">
  <!-- Flash Section -->
  <% if !flash.empty? %> <%= render 'shared/flash' %> <% end %>
  <div class="container-fluid text-center">
    <div>
      <%= will_paginate @pictures %>
    </div>
    <div class="row">
      <% @pictures.each do |picture| %>
        <a href="<%= picture_path(picture.id) %>" class="blog_links">
          <div class="col-lg-4 wow fadeIn">
            <div class="thumbnail box-shadow">
              <% if picture.picture.attached? %> <%= image_tag picture.picture.variant(resize: "500x500", auto_orient: true), alt: "Picture", class:
            "img-responsive center-picture" %> <% end %>
              <div>
                <% if logged_in? && current_user.admin? %>
                  <div>
                    <%= link_to "Delete", picture, method: :delete, class: "btn btn-danger top-margin-1-percent", data: { confirm: "Are you sure you want to delete
                this picture?" } %>
                  </div>
                <% end %>
              </div>
              <div class="caption text-center">
                <h5><%= picture.caption %></h5>
              </div>
            </div>
          </div>
        </a>
      <% end %>
    </div>
    <div>
      <%= will_paginate @pictures %>
    </div>
  </div>
</section>

app/views/pictures/new.html.erb
<section id="picture_new">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h4>Upload A New Picture</h4>
        <hr class="pageLine">
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 wow fadeIn">
        <%= form_for(@picture) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <div>
            <%= f.label :caption %>
            <%= f.trix_editor :caption, class: 'form-control' %>
          </div>
          <div class="picture">
            <%= f.label "Upload picture" %>
            <%= f.file_field :picture %>
          </div>
          <br>
          <div class="text-center">
            <%= f.submit "Upload Picture", class: "btn btn-default btn-lg buttonDropShadow" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
 

app/views/pictures/show.html.erb
<section id="show_picture">
  <div class="container-fluid">
    <!-- Flash Section -->
    <% if !flash.empty? %>
      <%= render 'shared/flash2' %>
    <% end %>
    <div class="row">
      <div class="col-lg-12">
        <div class="bottom-margin-30px">
          <% if @picture.picture.attached? %>
            <%= image_tag @picture.picture.variant(resize: "800x800", auto_orient: true), alt: "Picture", class: "img-responsive center-picture" %>
          <% end %>
        </div>
        <div class="row">
          <% if !@picture.comments.empty? %>
            <% @picture.comments.each do |comment| %>
              <div class="col-lg-10 col-lg-offset-1">
                <br>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><%= comment.author.name %> says:<span class="float-right"><%=time_ago_in_words(comment.created_at) %> ago</span> </h3>
                  </div>
                  <div class="panel-body">
                    <%= comment.content %>
                    <div class="float-right">
                      <%= link_to "Delete", comment, method: :delete, class: "btn btn-danger",
                                                        data: { confirm: "Are you sure you want to delete your comment?" } %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
          <div class="text-center">
            <% if !logged_in? %>
              <%= link_to "Please log in to comment", login_path, class: "btn btn-default btn-lg buttonDropShadow", role: "button" %>
            <% else %>
              <%= form_for [@story, Comment.new] do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :picture_id, value: @picture.id %>
                <%= f.text_area :content, placeholder: "Add a comment", class: "comment-area", cols: "100", rows: "5" %><br/>
                <%= f.submit "Leave a comment on this picture", class: "btn btn-default btn-lg buttonDropShadow" %>
              <% end %>
            <% end %>
          </div>
          <div class="text-center top-margin-1-percent">
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Edit this picture", edit_picture_path(@picture.id), class: "btn btn-default btn-lg buttonDropShadow", role: "button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
   